routes/web.php
<?php

use App\Job;

Route::get('/', function () {
    $jobs = Job::latest()->limit(5)->get();
    return view('welcome', compact('jobs'));
});

Route::get('about', 'PagesController@about')->name('about');
Route::get('contact', 'PagesController@contact')->name('contact');
Route::get('support', 'PagesController@support')->name('support');

Auth::routes();

Route::get('register/confirm/{token}', 'Auth\RegisterController@confirmEmail');

Route::get('home', 'HomeController@index')->name('home');

Route::get('jobs/category/{category}', 'JobCategoryController@show')->name('job-category.show');

Route::get('jobs', 'JobController@index')->name('jobs.index');
Route::get('jobs/{job}', 'JobController@show')->name('jobs.show');

Route::group(['middleware' => 'auth'], function () {
    Route::get('personal-details', 'UserController@show');

    Route::patch('personal-details', 'UserController@update');

    Route::resource('employment-history', 'EmploymentHistoryController');

    Route::get('computer-skills', 'ComputerSkillController@index')->name('computer-skills.index');
    Route::post('computer-skills', 'ComputerSkillController@store')->name('computer-skills.store');
    Route::delete('computer-skills/{id}', 'ComputerSkillController@destroy')->name('computer-skills.destroy');

    Route::get('education-background', 'EducationBackgroundController@index')->name('education-background.index');
    Route::get('education-background/create', 'EducationBackgroundController@create')->name('education-background.create');
    Route::post('education-background', 'EducationBackgroundController@store')->name('education-background.post');

    Route::resource('references', 'ReferenceController');

    Route::resource('professional-training', 'ProfessionalTrainingController');

    Route::resource('interests', 'InterestController');

    Route::resource('additional-skills', 'AdditionalSkillController');

    Route::get('my-cv', 'UserController@myCv')->name('my-cv');
});

/*
/-----------------------------------
/ Job Application
/ The process of applying for a job
*/
Route::post('jobs/{slug}/{job}/apply', 'UserController@storeJob')->name('job.apply');

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. 
|
*/

Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth', 'hr']], function () {

    // Dashboard
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // Jobs
    Route::get('dashboard/jobs', 'JobController@index')->name('dashboard.jobs.index');
    Route::get('dashboard/jobs/create', 'JobController@create')->name('dashboard.jobs.create');
    Route::get('dashboard/jobs/{job}/edit', 'JobController@edit')->name('dashboard.jobs.edit');
    Route::patch('dashboard/jobs/{job}', 'JobController@update')->name('dashboard.jobs.update');
    Route::post('dashboard/jobs', 'JobController@store')->name('dashboard.jobs.store');
    Route::get('dashboard/jobs/{slug}/{job}', 'JobController@show')->name('dashboard.jobs.show');
    Route::get('dashboard/jobs/{slug}/{job}/applicants/{applicant}', 'JobController@applicants')->name('dashboard.jobs.show.applicants.show');

    // Applicants
    Route::get('dashboard/applicants', 'ApplicantController@index')->name('dashboard.applicants.index');
    Route::get('dashboard/applicants/{applicant}', 'ApplicantController@show')->name('dashboard.applicants.show');
    
    Route::get('dashboard/applicants/{applicant}/profile', 'ApplicantController@profile')->name('dashboard.applicants.profile');

    // Interviews
    Route::post('dashboard/interviews/{job}/{applicant}', 'InterviewController@store')->name('dashboard.interviews.store');

    // Qualifications
    Route::resource('dashboard/qualification-level', 'QualificationsController');

});

// Settings
Route::group(['namespace' => 'Settings', 'middleware' => 'auth'], function () {
    Route::resource('settings/job-categories', 'JobCategoryController');

    Route::get('settings/computer-skills', 'ComputerSkillController@index')->name('settings.computer-skills.index');
    Route::get('settings/computer-skills/create', 'ComputerSkillController@create')->name('settings.computer-skills.create');
    Route::post('settings/computer-skills/', 'ComputerSkillController@store')->name('settings.computer-skills.store');
    Route::get('settings/computer-skill/{computerSkill}/edit', 'ComputerSkillController@edit')->name('settings.computer-skills.edit');
    Route::patch('settings/computer-skills/{computerSkill}', 'ComputerSkillController@update')->name('settings.computer-skills.update');
    Route::delete('settings/computer-skills/{computer-skill}', 'ComputerSkillController@destroy')->name('settings.computer-skills.destroy');
    
    Route::delete('settings/computer-skills/{computerSkill}', 'ComputerSkillController@destroy')->name('settings.computer-skills.destroy');
    Route::get('settings/competences', 'CompetenceController@index')->name('settings.competences.index');
    Route::get('settings/competences/create', 'CompetenceController@create')->name('settings.competences.create');
    Route::post('settings/competences/store', 'CompetenceController@store')->name('settings.competences.store');

    Route::get('settings/education-levels', 'EducationLevelController@index')->name('settings.education-levels.index');
    Route::get('settings/education-areas', 'EducationAreaController@index')->name('settings.education-areas.index');
    //Nationalities
    Route::get('settings/nationalities', 'NationalitiesController@index')->name('settings.nationalities.index');
    Route::get('settings/nationalities/create', 'NationalitiesController@create')->name('settings.nationalities.create');
    Route::post('settings/nationalities/store', 'NationalitiesController@store')->name('settings.nationalities.store');
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('primary-school', 'PrimarySchoolController@store')->name('primary-school.store');
    Route::post('ordinary-level', 'OrdinaryLevelController@store')->name('ordinary-level.store');
    Route::post('advanced-level', 'AdvancedLevelController@store')->name('advanced-level.store');
    Route::get('my-applications', function () {
       $jobs = auth()->user()->job_applications;
       return view('jobs.my-applications', compact('jobs'));
   })->name('my-applications');
    Route::resource('higher-education', 'HigherEducations');
});

/** Reports */
Route::group(['middleware' => 'auth', 'namespace' => 'Reports'], function () {
    Route::post('reports/jobs/{job}', 'ExportController@jobApplicants')->name('reports.jobs.applicants');

    Route::get('reports/jobs-with-applicants', 'ExportController@jobsWithApplicants')->name('reports.jobs-with-applicants');

    Route::get('reports/jobs-with-applicants-call-for-interview', 'ExportController@jobsWithApplicantsCallForInterview')->name('reports.jobs-with-applicants-call-for-interview');

    Route::get('reports/jobs-with-applicants-not-call-for-interview', 'ExportController@jobsWithApplicantsNotCallForInterview')->name('reports.jobs-with-applicants-not-call-for-interview');
});

Route::post('download', 'DownloadController@download')->name('download');
Route::post('preview', 'DownloadController@preview')->name('preview');

app/Reference.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reference extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ReferenceController.php
<?php

namespace App\Http\Controllers;

use App\Reference;
use Illuminate\Http\Request;

class ReferenceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $references = auth()->user()->references()->get();
        return view('references.index', compact('references'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('references.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'title' => 'required',
                'first_name' => 'required',
                'last_name' => 'required',
                'phone' => 'required',
                'email' => 'required',
                'institution' => 'required',
                'address' => 'required',
            ]);

        $reference = new Reference();
        $reference->title = $request->input('title');
        $reference->first_name = $request->input('first_name');
        $reference->middle_name = $request->input('middle_name');
        $reference->last_name = $request->input('last_name');
        $reference->phone = $request->input('phone');
        $reference->email = $request->input('email');
        $reference->institution = $request->input('institution');
        $reference->address = $request->input('address');
        $reference->user_id = auth()->id();
        $reference->save();

        $progress = auth()->user()->progress()->first();
        $progress->references = true;
        $progress->save();         

        flash('Reference added successfully')->success();

        return redirect('references');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Reference $reference
     * @return \Illuminate\Http\Response
     */
    public function show(Reference $reference)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Reference $reference
     * @return \Illuminate\Http\Response
     */
    public function edit(Reference $reference)
    {
        return view('references.edit', compact('reference'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Reference $reference
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Reference $reference)
    {
        $this->validate($request, [
                'title' => 'required',
                'first_name' => 'required',
                'last_name' => 'required',
                'phone' => 'required',
                'email' => 'required',
                'institution' => 'required',
                'address' => 'required',
            ]);
        
        $reference->title = $request->input('title');
        $reference->first_name = $request->input('first_name');
        $reference->middle_name = $request->input('middle_name');
        $reference->last_name = $request->input('last_name');
        $reference->phone = $request->input('phone');
        $reference->email = $request->input('email');
        $reference->institution = $request->input('institution');
        $reference->address = $request->input('address');
        $reference->user_id = auth()->id();
        $reference->save();

        flash('Reference successfully updated.')->success();

        return redirect('references');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Reference $reference
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reference $reference)
    {
        $reference->delete();

        flash('Reference successfully deleted.')->success();

        return redirect('references');
    }
}

resources/views/references/_form.blade.php
<div class="form-group">
    <label for="title" class="col-sm-3 control-label">Title</label>
    <div class="col-sm-5">
        <select name="title" id="title" class="form-control">
            <option value="">-Select-</option>
            <option value="Mr">Mr</option>
            <option value="Mrs">Mrs</option>
            <option value="Miss">Miss</option>
            <option value="Dr">Dr</option>
            <option value="Prof">Prof</option>
        </select>
    </div>
</div>

<div class="form-group">
    <label for="first_name" class="col-sm-3 control-label">First Name</label>
    <div class="col-sm-5">
        <input type="text"
               name="first_name"
               id="first_name"
               value="{{ $reference->first_name or old('first_name') }}"
               class="form-control"
               placeholder="First Name"
               required="required">
    </div>
</div>

<div class="form-group">
    <label for="middle_name" class="col-sm-3 control-label">Middle Name (Option)</label>
    <div class="col-sm-5">
        <input type="text"
               name="middle_name"
               id="middle_name"
               value="{{ $reference->middle_name or old('middle_name') }}"
               class="form-control"
               placeholder="Middle Name (Option)"
               required="required">
    </div>
</div>

<div class="form-group">
    <label for="last_name" class="col-sm-3 control-label">Last Name</label>
    <div class="col-sm-5">
        <input type="text"
               name="last_name"
               id="last_name"
               value="{{ $reference->last_name or old('last_name') }}"
               class="form-control"
               placeholder="Last Name"
               required="required">
    </div>
</div>

<div class="form-group">
    <label for="phone" class="col-sm-3 control-label">Phone</label>
    <div class="col-sm-5">
        <input type="tel"
               name="phone"
               id="phone"
               value="{{ $reference->phone or old('phone') }}"
               class="form-control"
               placeholder="+XXX XXX XXX XXX">
    </div>
</div>

<div class="form-group">
    <label for="phone" class="col-sm-3 control-label">Email</label>
    <div class="col-sm-5">
        <input type="email"
               name="email"
               id="email"
               value="{{ $reference->email or old('email') }}"
               class="form-control"
               placeholder="Email Address">
    </div>
</div>

<div class="form-group">
    <label for="institution" class="col-sm-3 control-label">Institution</label>
    <div class="col-sm-5">
        <input type="text"
               name="institution"
               id="institution"
               value="{{ $reference->institution or old('institution') }}"
               class="form-control"
               placeholder="Institution name">
    </div>
</div>

<div class="form-group">
    <label for="address" class="col-sm-3 control-label">Address</label>
    <div class="col-sm-5">
        <input type="text" name="address" id="address" value="{{ $reference->address or old('address') }}" class="form-control">
    </div>
</div>

resources/views/references/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @include('partials.sidebar')
        </div>
        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">Add New Reference</div>
                <div class="panel-body">
                    @include('errors.list')
                    <form action="{{ route('references.store') }}" method="POST" class="form-horizontal"
                    role="form">
                    {{ csrf_field() }}

                    @include('references._form')

                    <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/references/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @include('partials.sidebar')
            </div>
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Reference</div>

                    <div class="panel-body">
                        <form action="{{ route('references.update', $reference->id) }}" method="POST"
                              class="form-horizontal"
                              role="form">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            @include('references._form')

                            <div class="form-group">
                                <div class="col-sm-10 col-sm-offset-2">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/references/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            @include('partials.sidebar')
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading">My References</div>

                <div class="panel-body">
                    @if($references->count())
                    @foreach($references->chunk(3) as $referenceSet)
                    <div class="row">
                        @foreach($referenceSet as $reference)
                        <div class="col-sm-4">
                            <div class="thumbnail">
                                <div class="caption">
                                    <h3>
                                        {{ $reference->title }}.
                                        {{ $reference->first_name }}
                                        {{ $reference->middle_name }}
                                        {{ $reference->last_name }}
                                    </h3>
                                    <p>
                                        {{ $reference->institution }}
                                    </p>
                                    <p>
                                        Phone: {{ $reference->phone }}
                                    </p>
                                    <p>
                                        Email: {{ $reference->email }}
                                    </p>
                                    <p>
                                        <a class="btn btn-primary btn-sm"
                                        href="{{ route('references.edit', $reference->id) }}">Edit</a>
                                        <a class="btn btn-danger btn-sm" data-toggle="modal"
                                        href='#modal-id'>Delete</a>
                                        <div class="modal fade" id="modal-id">
                                            <div class="modal-dialog">
                                                <form method="POST"
                                                action="{{ route('references.destroy', $reference->id) }}">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}

                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close"
                                                        data-dismiss="modal" aria-hidden="true">
                                                        &times;
                                                    </button>
                                                    <h4 class="modal-title">Delete Reference</h4>
                                                </div>
                                                <div class="modal-body">
                                                    Are you sure that you want to permanently delete
                                                    <strong>
                                                        {{ $reference->title }}.
                                                        {{ $reference->first_name }}
                                                        {{ $reference->middle_name }}
                                                        {{ $reference->last_name }}
                                                    </strong>?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default"
                                                    data-dismiss="modal">Cancel
                                                </button>
                                                <button type="submit" class="btn btn-danger">
                                                    Delete
                                                </button>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </p>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
        @endforeach
        @else
        <div class="info">
            <p class="lead">
                You have 0 references
            </p>
        </div>
        @endif
    </div>
    <div class="panel-footer">
        <a href="{{ route('references.create') }}" class="btn btn-primary btn-sm">Add New</a>
    </div>
</div>
</div>
<div class="col-sm-2">
    
    @include('partials.applicant.progress', ['user' => Auth::user()])
    
</div> 
</div>
</div>
@endsection