routes/web.php
<?php

use App\Job;

Route::get('/', function () {
    $jobs = Job::latest()->limit(5)->get();
    return view('welcome', compact('jobs'));
});

Route::get('about', 'PagesController@about')->name('about');
Route::get('contact', 'PagesController@contact')->name('contact');
Route::get('support', 'PagesController@support')->name('support');

Auth::routes();

Route::get('register/confirm/{token}', 'Auth\RegisterController@confirmEmail');

Route::get('home', 'HomeController@index')->name('home');

Route::get('jobs/category/{category}', 'JobCategoryController@show')->name('job-category.show');

Route::get('jobs', 'JobController@index')->name('jobs.index');
Route::get('jobs/{job}', 'JobController@show')->name('jobs.show');

Route::group(['middleware' => 'auth'], function () {
    Route::get('personal-details', 'UserController@show');

    Route::patch('personal-details', 'UserController@update');

    Route::resource('employment-history', 'EmploymentHistoryController');

    Route::get('computer-skills', 'ComputerSkillController@index')->name('computer-skills.index');
    Route::post('computer-skills', 'ComputerSkillController@store')->name('computer-skills.store');
    Route::delete('computer-skills/{id}', 'ComputerSkillController@destroy')->name('computer-skills.destroy');

    Route::get('education-background', 'EducationBackgroundController@index')->name('education-background.index');
    Route::get('education-background/create', 'EducationBackgroundController@create')->name('education-background.create');
    Route::post('education-background', 'EducationBackgroundController@store')->name('education-background.post');

    Route::resource('references', 'ReferenceController');

    Route::resource('professional-training', 'ProfessionalTrainingController');

    Route::resource('interests', 'InterestController');

    Route::resource('additional-skills', 'AdditionalSkillController');

    Route::get('my-cv', 'UserController@myCv')->name('my-cv');
});

/*
/-----------------------------------
/ Job Application
/ The process of applying for a job
*/
Route::post('jobs/{slug}/{job}/apply', 'UserController@storeJob')->name('job.apply');

/*
|--------------------------------------------------------------------------
| Dashboard Routes
|--------------------------------------------------------------------------
|
| Here is where you can register dashboard routes for your application. 
|
*/

Route::group(['namespace' => 'Dashboard', 'middleware' => ['auth', 'hr']], function () {

    // Dashboard
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // Jobs
    Route::get('dashboard/jobs', 'JobController@index')->name('dashboard.jobs.index');
    Route::get('dashboard/jobs/create', 'JobController@create')->name('dashboard.jobs.create');
    Route::get('dashboard/jobs/{job}/edit', 'JobController@edit')->name('dashboard.jobs.edit');
    Route::patch('dashboard/jobs/{job}', 'JobController@update')->name('dashboard.jobs.update');
    Route::post('dashboard/jobs', 'JobController@store')->name('dashboard.jobs.store');
    Route::get('dashboard/jobs/{slug}/{job}', 'JobController@show')->name('dashboard.jobs.show');
    Route::get('dashboard/jobs/{slug}/{job}/applicants/{applicant}', 'JobController@applicants')->name('dashboard.jobs.show.applicants.show');

    // Applicants
    Route::get('dashboard/applicants', 'ApplicantController@index')->name('dashboard.applicants.index');
    Route::get('dashboard/applicants/{applicant}', 'ApplicantController@show')->name('dashboard.applicants.show');
    
    Route::get('dashboard/applicants/{applicant}/profile', 'ApplicantController@profile')->name('dashboard.applicants.profile');

    // Interviews
    Route::post('dashboard/interviews/{job}/{applicant}', 'InterviewController@store')->name('dashboard.interviews.store');

    // Qualifications
    Route::resource('dashboard/qualification-level', 'QualificationsController');

});

// Settings
Route::group(['namespace' => 'Settings', 'middleware' => 'auth'], function () {
    Route::resource('settings/job-categories', 'JobCategoryController');

    Route::get('settings/computer-skills', 'ComputerSkillController@index')->name('settings.computer-skills.index');
    Route::get('settings/computer-skills/create', 'ComputerSkillController@create')->name('settings.computer-skills.create');
    Route::post('settings/computer-skills/', 'ComputerSkillController@store')->name('settings.computer-skills.store');
    Route::get('settings/computer-skill/{computerSkill}/edit', 'ComputerSkillController@edit')->name('settings.computer-skills.edit');
    Route::patch('settings/computer-skills/{computerSkill}', 'ComputerSkillController@update')->name('settings.computer-skills.update');
    Route::delete('settings/computer-skills/{computer-skill}', 'ComputerSkillController@destroy')->name('settings.computer-skills.destroy');
    
    Route::delete('settings/computer-skills/{computerSkill}', 'ComputerSkillController@destroy')->name('settings.computer-skills.destroy');
    Route::get('settings/competences', 'CompetenceController@index')->name('settings.competences.index');
    Route::get('settings/competences/create', 'CompetenceController@create')->name('settings.competences.create');
    Route::post('settings/competences/store', 'CompetenceController@store')->name('settings.competences.store');

    Route::get('settings/education-levels', 'EducationLevelController@index')->name('settings.education-levels.index');
    Route::get('settings/education-areas', 'EducationAreaController@index')->name('settings.education-areas.index');
    //Nationalities
    Route::get('settings/nationalities', 'NationalitiesController@index')->name('settings.nationalities.index');
    Route::get('settings/nationalities/create', 'NationalitiesController@create')->name('settings.nationalities.create');
    Route::post('settings/nationalities/store', 'NationalitiesController@store')->name('settings.nationalities.store');
});

Route::group(['middleware' => 'auth'], function () {
    Route::post('primary-school', 'PrimarySchoolController@store')->name('primary-school.store');
    Route::post('ordinary-level', 'OrdinaryLevelController@store')->name('ordinary-level.store');
    Route::post('advanced-level', 'AdvancedLevelController@store')->name('advanced-level.store');
    Route::get('my-applications', function () {
       $jobs = auth()->user()->job_applications;
       return view('jobs.my-applications', compact('jobs'));
   })->name('my-applications');
    Route::resource('higher-education', 'HigherEducations');
});

/** Reports */
Route::group(['middleware' => 'auth', 'namespace' => 'Reports'], function () {
    Route::post('reports/jobs/{job}', 'ExportController@jobApplicants')->name('reports.jobs.applicants');

    Route::get('reports/jobs-with-applicants', 'ExportController@jobsWithApplicants')->name('reports.jobs-with-applicants');

    Route::get('reports/jobs-with-applicants-call-for-interview', 'ExportController@jobsWithApplicantsCallForInterview')->name('reports.jobs-with-applicants-call-for-interview');

    Route::get('reports/jobs-with-applicants-not-call-for-interview', 'ExportController@jobsWithApplicantsNotCallForInterview')->name('reports.jobs-with-applicants-not-call-for-interview');
});

Route::post('download', 'DownloadController@download')->name('download');
Route::post('preview', 'DownloadController@preview')->name('preview');

app/Http/Controllers/Dashboard/ApplicantController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApplicantController extends Controller
{
    public function index()
    {
    	$applicants = User::with('job_applications')->has('job_applications')->withCount('job_applications')->latest()->paginate(5);
    	return view('dashboard.applicants.index', compact('applicants'));
	}

	public function show($id)
	{
		$applicant = User::with('job_applications')->findOrFail($id);
		return view('dashboard.applicants.show', compact('applicant'));
	}

	public function profile($id)
	{
		$applicant = User::with('job_applications')->findOrFail($id);
		return view('dashboard.applicants.profile', compact('applicant'));
	}
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Job;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        $jobsCount = Job::count();
        $usersCount = User::count();

        $jobs = Job::withCount('applicants')->with('applicants')->has('applicants')->get();

        $jobsWithApplicantsCalledForInterview = Job::has('applicants')->with(['applicants' => function ($query) {
        	$query->where('called_for_interview', 1)->has('job_applications');
        }])->get();

        $jobsWithApplicantsNotCalledForInterview = Job::has('applicants')->with(['applicants' => function ($query) {
        	$query->where('called_for_interview', 0);
        }])->get();

        return view('dashboard.index', compact('jobsCount', 'usersCount', 'jobs', 'jobsWithApplicantsCalledForInterview', 'jobsWithApplicantsNotCalledForInterview'));
    }
}

app/Http/Controllers/Dashboard/InterviewController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Job;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class InterviewController extends Controller
{
    public function store($jobId, $applicantId)
    {
        $job = Job::findOrFail($jobId);
        $applicant = User::findOrFail($applicantId);

        $pivot = $job->applicants()->whereUserId($applicant->id)->first()->pivot;
        $pivot->called_for_interview = true;
        $pivot->save();

        flash('Applicant successfully called for interview.')->success()->important();

        return redirect()->route('dashboard.jobs.show', [$job->slug, $job->id]);
    }
}

app/Http/Controllers/Dashboard/JobController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Job;
use App\User;
use App\JobCategory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class JobController extends Controller
{
    public function index()
    {
        $jobs = Job::withCount(['applicants' => function ($query) {
            $query->has('ordinaryLevel');
        }])->latest()->get();

        return view('dashboard.jobs.index', compact('jobs'));
    }

    public function create()
    {
        $jobCategories = JobCategory::get();
        return view('dashboard.jobs.create', compact('jobCategories'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'job_category_id' => 'required',
            'body' => 'required',
            'positions' => 'required',
        ]);

        $jobVacancy = new Job();
        $jobVacancy->title = $request->input('title');
        $jobVacancy->slug = str_slug($request->input('title'), '-');
        $jobVacancy->body = nl2br(htmlentities($request->input('body'), ENT_QUOTES, 'UTF-8'));
        $jobVacancy->positions = $request->input('positions');
        $jobVacancy->user_id = auth()->id();
        $jobVacancy->status = false;
        $jobVacancy->closed_at = $request->input('closed_at');
        $jobVacancy->job_category_id = $request->input('job_category_id');
        $jobVacancy->save();

        flash('Job vacancy posted successfully')->success();

        return redirect()->route('dashboard.jobs.index');
    }

    public function show($slug, $id)
    {
        $job = Job::with('applicants')->whereId($id)->whereSlug($slug)->firstOrFail();

        $applicants = $job->applicants()->has('ordinaryLevel')->get();

        return view('dashboard.jobs.show', compact('job', 'applicants'));
    }

    public function applicants($slug, $jobId, $applicantId)
    {
        $applicant = User::with('job_applications')->findOrFail($applicantId);
        $job = Job::whereId($jobId)->whereSlug($slug)->firstOrFail();

        return view('dashboard.applicants.show', compact('applicant', 'job'));
    }

    public function edit($id)
    {
        $job = Job::findOrFail($id);
        $jobCategories = JobCategory::get();
        return view('dashboard.jobs.edit', compact('job', 'jobCategories'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'job_category_id' => 'required',
            'body' => 'required',
            'positions' => 'required',
        ]);

        $jobVacancy = Job::findOrFail($id);

        $jobVacancy->title = $request->input('title');
        $jobVacancy->slug = str_slug($request->input('title'), '-');
        $jobVacancy->body = nl2br(htmlentities($request->input('body'), ENT_QUOTES, 'UTF-8'));
        $jobVacancy->positions = $request->input('positions');
        $jobVacancy->user_id = auth()->id();
        $jobVacancy->status = false;
        $jobVacancy->closed_at = $request->input('closed_at');
        $jobVacancy->job_category_id = $request->input('job_category_id');
        $jobVacancy->save();

        flash('Job vacancy updateed successfully')->success();

        return redirect()->route('dashboard.jobs.index');        
    }
}

app/Http/Controllers/Dashboard/QualificationsController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Qualification;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class QualificationsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $qualifications = Qualification::orderBy('name')->get();
        return view('dashboard.qualifications.index', compact('qualifications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.qualifications.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
        ]);

        $qualification = new Qualification;

        $qualification->name = $request->name;
        $qualification->description = $request->description;
        $qualification->save();

        flash('Qualification Level posted successfully')->success();

        return redirect('/dashboard/qualification-level');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Qualification  $qualification
     * @return \Illuminate\Http\Response
     */
    public function show(Qualification $qualification)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Qualification  $qualification
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $qualification = Qualification::findOrFail($id);
        return view('dashboard.qualifications.edit', compact('qualification'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Qualification  $qualification
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
        ]);

        $qualification = Qualification::findOrFail($id);

        $qualification->name = $request->name;
        $qualification->description = $request->description;
        $qualification->save();

        flash('Qualification Level updated successfully')->success();

        return redirect('/dashboard/qualification-level');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Qualification  $qualification
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $qualification = Qualification::findOrFail($id);

        $qualification->delete();

        flash('Qualification Level deleted successfully')->success();

        return redirect('/dashboard/qualification-level');

    }
}

resources/views/dashboard/applicants/index.blade.php
@extends('layouts.app')

@section('title', 'Job Applicants')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @include('dashboard.partials.sidebar')
            </div>
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">Job Applicants</div>

                    <div class="panel-body">
                        @if($applicants->count())
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered table-responsive">
                                    <thead>
                                        <tr>
                                            <th class="text-right">SN</th>
                                            <th>Name</th>
                                            <th>Phone</th>
                                            <th>Email</th>
                                            <th>Gender</th>
                                            <th>Jobs Applied</th>
                                            <th>Registered</th>
                                            <th>Profile</th>
                                            <th>CV</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $i=1 @endphp
                                        @foreach($applicants as $applicant)
                                        <tr>
                                            <td class="text-right">{{ $i++ }}.</td>
                                            <td>
                                                  {{ $applicant->first_name }}
                                                  {{ $applicant->middle_name }}
                                                  {{ $applicant->last_name }}
                                            </td>
                                            <td>{{ $applicant->phone }}</td>
                                            <td>{{ $applicant->email }}</td>
                                            <td>{{ $applicant->gender }}</td>
                                            <td>{{ $applicant->job_applications_count }}</td>
                                            <td>{{ $applicant->created_at->toFormattedDateString() }}</td>
                                            <td>
                                                <a href="{{ route('dashboard.applicants.profile', $applicant->id) }}">
                                                    Click to view
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{{ route('dashboard.applicants.show', [$applicant->id]) }}">
                                                    Click to view
                                                </a>
                                            </td>
                                        </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <p class="lead">
                                {{ $applicants->count() }} applicants
                            </p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/applicants/profile.blade.php
@extends('layouts.app')

@section('title', $applicant->first_name .' '. $applicant->middle_name .' '. $applicant->last_name)

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @include('dashboard.partials.sidebar')
            </div>
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">Profile of {{ $applicant->first_name .' '. $applicant->middle_name .' '. $applicant->last_name }}</div>

                    <div class="panel-body">
                        
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Jobs Applied ({{ $applicant->job_applications()->count() }})</h3>
                    </div>
                    <div class="panel-body">
                        
                        @if($applicant->job_applications()->count())
                            <div class="table-responsive">
                                <table class="table table-hover table-bordered">
                                    <thead>
                                        <tr>
                                            <th>SN</th>
                                            <th>Title</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @php $i = 1 @endphp
                                        @foreach($applicant->job_applications as $job)
                                            <tr>
                                                <td>{{ $i++ }}.</td>
                                                <td>{{ $job->title }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        @else
                            <p class="text-center">No job applied</p>
                        @endif

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/applicants/show.blade.php
@extends('layouts.app')

@section('title', $applicant->first_name .' '. $applicant->middle_name .' '. $applicant->last_name)

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                @include('dashboard.partials.sidebar')
            </div>
            <div class="col-md-10">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ $applicant->first_name .' '. $applicant->middle_name .' '. $applicant->last_name }}</div>

                    <div class="panel-body">
                        @include('partials.cv', ['user' => $applicant])
                    </div>
                    @empty($job)
                        <div class="alert alert-warning">
                            <strong>Note!</strong> This person has not applied for any job
                        </div>
                    @endempty
                </div>
            </div>
        </div>
    </div>
@endsection